In [63]:
### surgery?, Age, rectal temperature, pulse, temperature of extremities, peripheral pulse, mucous membranes, capillary refill time

import pandas as pd
import numpy as np
pd.options.mode.chained_assignment = None 

data = pd.read_csv('horse_data.csv', header=None, na_values = ['?'])
data.columns = ['surgery?', 'Age', 'hospital_number', 'rectal_temperature', 'pulse', 'respiratory_rate', 'temperature_of_extremities', 
               'peripheral_pulse', 'mucous_membranes', 'capillary_refill_time', 'pain', 'peristalsis', 'abdominal_distension',
               'nasogastric_tube', 'nasogastric_reflux', 'nasogastric_reflux_PH', 'rectal_examination', 'abdomen', 'packed_cell_volume',
               'total_protein', 'abdominocentesis_appearance', 'abdomcentesis_total_protein', 'outcome', 'surgical lesion?',
               '25_type_of_lesion', '26_type_of_lesion', '27_type_of_lesion', 'cp_data']

df = data[['surgery?', 'Age', 'rectal_temperature', 'pulse', 'temperature_of_extremities', 'peripheral_pulse', 'mucous_membranes', 'capillary_refill_time']]

temp_range = max(df['rectal_temperature']) - min(df['rectal_temperature'])
print('Размах по температуре:', temp_range)
print('Среднее арифметическое по температуре:', df['rectal_temperature'].mean())
print('Значение моды по температуре:', df['rectal_temperature'].mode()[0])
print('Значение медианы по температуре:', df['rectal_temperature'].median())
print('СКО по температуре:', df['rectal_temperature'].std())
print('Дисперсия по температуре:', df['rectal_temperature'].var())
Q1 = df['rectal_temperature'].quantile(0.25)
Q3 = df['rectal_temperature'].quantile(0.75)
IQR = Q3 - Q1
print('1я квартиль по температуре:', Q1)
print('3я квартиль по температуре:', Q3)
print('Межквартильный размах по температуре:', IQR)

print()

pulse_range = max(df['pulse']) - min(df['pulse'])
print('Размах по пульсу:', pulse_range)
print('Среднее арифметическое по пульсу:', df['pulse'].mean())
print('Значение моды по пульсу:', df['pulse'].mode()[0])
print('Значение медианы по пульсу:', df['pulse'].median())
print('СКО по пульсу:', df['pulse'].std())
print('Дисперсия по пульсу:', df['pulse'].var())
Q1_2 = df['pulse'].quantile(0.25)
Q3_2 = df['pulse'].quantile(0.75)
IQR_2 = Q3_2 - Q1_2
print('1я квартиль по пульсу:', Q1_2)
print('3я квартиль по пульсу:', Q3_2)
print('Межквартильный размах по пульсу:', IQR_2)

#на основании полученных данных о распределении температуры лошадей видим, что среднее значение
#38.2 больше нормы 37.8, т.е. температура большинства больше нормального значения, что может говорить о наличии повреждений
#у большинства поступивших на госпитализацию.

#пульс большинства также гораздо выше нормального значения, что говорит о том, что у большинства поступивших животных 
#вероятно были болезненные повреждения и шок кровообращения. Значение дисперсии и размаха относительно 3й квартили указывает
#на то, что значения данного поля следует проверить на наличие выбросов.

Размах по температуре: 5.399999999999999
Среднее арифметическое по температуре: 38.16791666666669
Значение моды по температуре: 38.0
Значение медианы по температуре: 38.2
СКО по температуре: 0.7322886641121578
Дисперсия по температуре: 0.5362466875871686
1я квартиль по температуре: 37.8
3я квартиль по температуре: 38.5
Межквартильный размах по температуре: 0.7000000000000028

Размах по пульсу: 154.0
Среднее арифметическое по пульсу: 71.91304347826087
Значение моды по пульсу: 48.0
Значение медианы по пульсу: 64.0
СКО по пульсу: 28.630556660735003
Дисперсия по пульсу: 819.7087747035575
1я квартиль по пульсу: 48.0
3я квартиль по пульсу: 88.0
Межквартильный размах по пульсу: 40.0

In [64]:
print('Анализ на выбросы по значениям температуры:')
lower_temp = Q1 - (1.5 * IQR)
upper_temp = Q3 + (1.5 * IQR)
remove_temp = df[df['rectal_temperature'].between(lower_temp, upper_temp, inclusive=True)]
pd.concat([df, remove_temp]).drop_duplicates(keep=False).sort_values('rectal_temperature').dropna(subset=['rectal_temperature'])

#получилось 12 значений, считающихся выбосами. Среди них не замечено ничего подозрительного - каждое вполне допустимо.
#удалять нет необходимости.

Анализ на выбросы по значениям температуры:

,surgery?,Age,rectal_temperature,pulse,temperature_of_extremities,peripheral_pulse,mucous_membranes,capillary_refill_time
44,1.0,1,35.4,140.0,3.0,3.0,4.0,2.0
141,2.0,1,36.0,42.0,NaN,NaN,5.0,1.0
238,2.0,1,36.1,88.0,3.0,3.0,3.0,1.0
80,1.0,1,36.4,98.0,3.0,3.0,4.0,1.0
118,1.0,1,36.5,78.0,1.0,NaN,1.0,1.0
298,1.0,1,36.5,100.0,3.0,3.0,3.0,1.0
251,2.0,1,36.6,42.0,3.0,3.0,2.0,1.0
99,2.0,1,39.6,108.0,3.0,3.0,6.0,2.0
75,1.0,9,39.7,100.0,3.0,3.0,5.0,2.0
20,1.0,1,39.9,72.0,1.0,1.0,5.0,2.0
281,2.0,1,40.0,78.0,3.0,3.0,5.0,1.0
259,1.0,1,40.8,72.0,3.0,3.0,1.0,1.0

In [65]:
print('Анализ на выбросы по значениям пульса:')
lower_temp = Q1_2 - (1.5 * IQR_2)
upper_temp = Q3_2 + (1.5 * IQR_2)
remove_temp = df[df['pulse'].between(lower_temp, upper_temp, inclusive=True)]
pd.concat([df, remove_temp]).drop_duplicates(keep=False).sort_values('pulse').dropna(subset=['pulse'])

#сами значения кажутся всерьез завышенными, если сравнивать с нормой и параметрами, вычисленными в предыдущей задаче, но видим,
#что температура данных примеров также довольно сильно, но не критично, повышена, что говорит о вероятном наличии повреждений.
#в данном случае серьезно повышенный пульс также допустим и значения стоит оставить.

Анализ на выбросы по значениям пульса:

,surgery?,Age,rectal_temperature,pulse,temperature_of_extremities,peripheral_pulse,mucous_membranes,capillary_refill_time
41,2.0,9,39.0,150.0,NaN,NaN,NaN,NaN
275,1.0,9,38.8,150.0,1.0,3.0,6.0,2.0
55,1.0,9,38.6,160.0,3.0,NaN,5.0,1.0
3,1.0,9,39.1,164.0,4.0,1.0,6.0,2.0
255,1.0,9,38.8,184.0,1.0,NaN,1.0,1.0

In [66]:
#в датафрейме всего 300 строк, 26 из них те, у которых > 5 незаполненных колонок. Удаляем их, т.к. количество по отношению
#к общему несущественно и критично влиять на статистику не должно

df.dropna(thresh=5, inplace=True)

#для 1 строки, где surgery? = NaN в соответствии с тем, что лошадь взрослая - Age = 1 - и пульс при норме для взрослых 30-40
#равен 48, то вероятнее всего, у лошади была сильная боль и потребовалась операция - ставим surgery? = 1

df.loc[df['surgery?'].isnull()] = 1

#начнем с колонки pulse, т.к. это значение необходимо для вычисления значения temperature_of_extremities, от которого, в свою очередь 
#зависит rectal_temperature. Пульс может указывать на возраст лошади - для взрослых, например, нормально значение 30 - 40
#вычисляем медиану для каждого вида значения поля Age и заполняем ей пропуски в pulse

df['pulse'].fillna(df.groupby('Age')['pulse'].transform('median'), inplace=True)

#если высокий пульс, вероятно, что животное в шоке. Этому состоянию обычно соответствуют значения 3 - 4 поля temperature_of_extremities
#вводим категории для значений пульса:
#1 - пульс 0-19 (низкий), 2 - пульс 20-29 (норма для молодых животных), 3 - пульс 30-39 (норма для пожилых животных),
#4 - пульс 40-99 (повышенный пульс, вероятно соответствует значению 3 поля temperature_of_extremities),
#5 - пульс выше 100 (сильно повышенный пульс, вероятно соответствует значению 4 поля temperature_of_extremities)

df['pulse_category'] = pd.cut(df['pulse'], [0, 20, 30, 40, 100, np.inf], labels=[1,2,3,4,5])

#по каждой категории 'pulse_category' вычисляем значение медианы и заменяем им отстуствующие значения для таких же категорий в
#temperature_of_extremities

df['temperature_of_extremities'].fillna(df.groupby('pulse_category')['temperature_of_extremities'].transform('median'), inplace=True)

#в отсутствующие значения поля rectal_temperature проставляем значения медианы по температуре с группировкой по temperature_of_extremities

df['rectal_temperature'].fillna(df.groupby('temperature_of_extremities')['rectal_temperature'].transform('median'), inplace=True)

#в поле capillary_refill_time всего 8 отсутствующих значений - можно их заполнить медианой по этому столбцу
#ошибочное заполнение не должно повлиять на статистику по данным в целом

df['capillary_refill_time'].fillna(df['capillary_refill_time'].median(), inplace=True)

#отсутствующие значения в mucous_membranes заменяем медианой по сapillary_refill_time

df['mucous_membranes'].fillna(df.groupby('capillary_refill_time')['mucous_membranes'].transform('median'), inplace=True)

#отсутствующие значения в peripheral_pulse заменяем медианой по сapillary_refill_time, mucous_membranes

df['peripheral_pulse'].fillna(df.groupby(['capillary_refill_time', 'mucous_membranes'])['peripheral_pulse'].transform('median'), inplace=True)

print('Всего:\n', df.count(),'\n')
print('Нулевые:\n', df.isnull().sum())

df.describe()

Всего:
 surgery?                      274
Age                           274
rectal_temperature            274
pulse                         274
temperature_of_extremities    274
peripheral_pulse              274
mucous_membranes              274
capillary_refill_time         274
pulse_category                274
dtype: int64

Нулевые:
 surgery?                      0
Age                           0
rectal_temperature            0
pulse                         0
temperature_of_extremities    0
peripheral_pulse              0
mucous_membranes              0
capillary_refill_time         0
pulse_category                0
dtype: int64

,surgery?,Age,rectal_temperature,pulse,temperature_of_extremities,peripheral_pulse,mucous_membranes,capillary_refill_time
count,274.000000,274.000000,274.000000,274.000000,274.000000,274.000000,274.000000,274.00000
mean,1.408759,1.525547,38.033029,71.284672,2.383212,1.967153,2.824818,1.29562
std,0.492504,1.985590,2.342847,27.709759,1.021316,1.035460,1.582402,0.47291
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000
25%,1.000000,1.000000,37.900000,48.250000,1.000000,1.000000,1.000000,1.00000
50%,1.000000,1.000000,38.100000,60.000000,3.000000,1.000000,3.000000,1.00000
75%,2.000000,1.000000,38.500000,88.000000,3.000000,3.000000,4.000000,2.00000
max,2.000000,9.000000,40.800000,184.000000,4.000000,4.000000,6.000000,3.00000